######  data config start ######
spring:
  jpa:
     properties:
        hibernate:
           hbm2ddl:
              auto: update
           dialect: org.hibernate.dialect.MySQL5InnoDBDialect
     show-sql: true
#####   mail setting begin #####
  mail:
     host: smtp.163.com
     username: jiang_lei23@163.com
     password: jl12345678
     properties:
        mail:
           smtp:
              auth: true
              starttls:
                 enable: true
                 required: true

  thymeleaf:
     cache: false
  profiles:
     active: dev
mail:
  subject:
     forgotpassword: \u5BC6\u7801\u91CD\u7F6E\u90AE\u4EF6
  content:
     forgotpassword: \u8BF7\u70B9\u51FB\u4EE5\u4E0B\u5730\u5740:<br /><a href='{0}'>\u91CD\u7F6E\u5BC6\u7801</a>

forgotpassword:
  url: http://favorites.ren/newPassword

static:
  url: /work/graduation/src/main/resources/static/
file:
  profilepictures:
     url: img/
  backgroundpictures:
     url: file/backgroundpictures/
